### ISSUE TITLE
Getting Started Documentation

### ISSUE THREAD

**Issue by TylerGubala** [odwdinc/SSBU_Amiibo#1]
Could there be an update to the documentation for a better "getting started" guide?

For instance (Python 3.7 64 bit windows assumed):

# Getting Started

  1. `git clone https://github.com/odwdinc/SSBU_Amiibo.git`
  2. `cd SSBU_Amiibo`
  3. `py -3.6-64 -m venv venv`
  4. `./venv/Scripts/Activate`
  5. `py -m pip install --upgrade pip`
  6. `py -m pip install cryptography pyamiibo`
  7.  Run `py ui.py`

The below was what I needed to do to get this up and running, which was easy enough to do, but considering that you'll probably get a lot of kids trying to use the code, it's probably best to have as clear of documentation as you can provide.

Nice utility though!

**Comment by odwdinc** [comment]
I will have some time this weekend to clean the code, docs, and UI, Thank you for the input! If you wanted to submit a PR I would be more then happy to approve it!
I do know there is people on Linux and windows so something that would help bout out is me current plan

**Comment by odwdinc** [comment]
this should be good now
