### ISSUE TITLE
Readme Instructions

### ISSUE THREAD

**Issue by Pompanomike69** [odwdinc/SSBU_Amiibo#11]
The entire read me file is messed up, it makes no sense, plus i cant find anything it says to do after the installation of git and python. all it shows me is just "Setup" and thats it, nothing else added

**Comment by Pompanomike69** [comment]
Another thing, your instructions are terrible, at no point does it tell you how to properly build it, when you do build it, you get nothing. when you run
**$env:Path += "$env:APPDATA\Python\Python37\Scripts;"
ssbu_amiibo.exe**
you get absolutely nothing.
it returns an error, and nothing happens, you should give us an email or something to contact you on

**Comment by BaReinhard** [comment]
I would suggest looking at #14 for clearer instructions on how to use this application.

**Comment by odwdinc** [comment]
let me know if the updates make this more clear.
