### ISSUE TITLE
Fail to Decode from AmiiboAPI

### ISSUE THREAD

**Issue by rlziii** [odwdinc/SSBU_Amiibo#15]
Some of AmiiboAPI's JSON responses contain newline characters.  Since `sbuu.GetWebData(self)` attempts to decode the JSON via `HTTPResponse.readline()` the decode will fail in cases where the JSON response contains these newline characters with the following error:

```
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```

Instead, `GetWebData()` should use `HTTPResponse.read()` to ensure it reads the entire JSON response even if newlines are present.

**Comment by odwdinc** [comment]
Close with merge
