### ISSUE TITLE
Amiibo not loading nor decrypting...

### ISSUE THREAD

**Issue by MochiBluse** [odwdinc/SSBU_Amiibo#17]
As the title says, it can't open amiibo files. All bin and bind files appear as 1kb and when opened nothing changes on the gui...

**Comment by AceHack** [comment]
I have the same problem, any update?

**Comment by AceHack** [comment]
I got it to work by pulling down the code locally and applying this PR
https://github.com/odwdinc/SSBU_Amiibo/pull/16

**Comment by MochiBluse** [comment]
How do I do that? I am quite new at this and checked the PR but I still don't know what to modify in the file

**Comment by odwdinc** [comment]
No need, the fix is merge just now, just re-download

**Comment by MochiBluse** [comment]
No changes yet... Am I the only one with this problem? Maybe my key_retail.bin is outdated or something but I can't find where to download it

**Comment by odwdinc** [comment]
https://github.com/odwdinc/SSBU_Amiibo/releases/tag/v0.0.5
