### ISSUE TITLE
Changes Not made

### ISSUE THREAD

**Issue by Payme42** [odwdinc/SSBU_Amiibo#18]
![image](https://user-images.githubusercontent.com/45109917/103921476-8e95a400-50e0-11eb-96b2-5771cef45f73.png)
this keeps happinging and i used the exe, no stat changes are made an i have 4 marios now not even hacked. help

**Comment by Payme42** [comment]
also the valuse and their uses are highly unclear, is L:earn On / Off checked mean on or off? ect. ewhat are colors and gifts

**Comment by odwdinc** [comment]
The exe is not been updated. Please use the updated source code or for new release with the updates

**Comment by Payme42** [comment]
i did the setup but how do i run lol.

**Comment by Payme42** [comment]
with python
