### ISSUE TITLE
Key_retail.bin

### ISSUE THREAD

**Issue by evan6800** [odwdinc/SSBU_Amiibo#20]
just a little confuzed on how to get the key.retail.bin file to get the program to work

**Comment by odwdinc** [comment]
Are your asking abut the file name?
Needs to be key_retail.bin vs  key.retail.bin

**Comment by evan6800** [comment]
its ok i fixed it tho i do have another issue. i used the program for one amiibo and it worked fine. but im trying to encrypt to finish it off but no file appears after i encrypt amiibo. it closes the save window but no file shows up where i saved it. this only happend the second time i tried
