### ISSUE TITLE
No "Decrypt Amiibo" option?

### ISSUE THREAD

**Issue by qwertyuiopasd1113** [odwdinc/SSBU_Amiibo#22]
When I go into File there is no "Decrypt Amiibo" option

**Comment by odwdinc** [comment]
Best to compare the [MD5 hash](http://onlinemd5.com/) of the **key_retail.bin**

45FD53569F5765EEF9C337BD5172F937

**Comment by qwertyuiopasd1113** [comment]
Nevermind, I didn't have the key_retail.bin
