### ISSUE TITLE
Decrypting Amiibo Doesn't Work

### ISSUE THREAD

**Issue by UserUnavailablee** [odwdinc/SSBU_Amiibo#24]
Whenever I try to decrypt a .bin file this error shows up. Any help?

![image](https://user-images.githubusercontent.com/91800133/135727673-fb81e0a2-9de2-40a0-8913-a72eecc96018.png)

**Comment by DonutKink** [comment]
I am having the same issue, I have tried googling it and I have no clue how to actually use python or why any of it could mean. please send help. I have been at this with a friend for 4 hours.

**Comment by Retr089** [comment]
I am also getting the same error, and I have downloaded the most recent release of the program. I know it has worked before, but now it doesn't.

**Comment by Tanish-Khanna** [comment]
have you put your key_retail file in the right place?

**Comment by Retr089** [comment]
> have you put your key_retail file in the right place?

True, but isn't that somewhat irrelevant? It's an ssl certificate error.

**Comment by odwdinc** [comment]
This looks as it was due to https://www.amiiboapi.com/ SSL Cert. this should no-longer be a problem. 
See for more info.
https://github.com/odwdinc/SSBU_Amiibo/blob/32d73a2a29ae9854a92a543845e605a3ad199906/src/ssbu_amiibo/amiibo_class.py#L115
