### ISSUE TITLE
Some amiibos unreadable

### ISSUE THREAD

**Issue by CatapultingWizard** [odwdinc/SSBU_Amiibo#7]
When decrypting the Donkey Kong, Pikachu, Diddy Kong, or Ryu amiibo, it refuses to load. While it successfully decrypts the amiibo, loading the newly decrypted file still doesn't work. The console shows this whenever I attempted to decrypt and load the Donkey Kong amiibo bin file.
![Screenshot (14)](https://user-images.githubusercontent.com/44379630/71898899-189edb80-3120-11ea-983e-bb150d9c5e1e.png)

**Comment by odwdinc** [comment]
yah i'm seeing some strange ID's on some.
and there then not found in https://www.amiiboapi.com/
I worked a temp fix for now but need to look over the code to see if its still working overall.
