### ISSUE TITLE
TagMo doesn't recognise the moded .bin file

### ISSUE THREAD

**Issue by Ciel-MC** [odwdinc/SSBU_Amiibo#8]
I decrypted an amiibo bin file and modded it, then saved and encrypted it back, but when I put the encrypted .bin file into the tagmo folder, it's not recognized as an amiibo bin file while the original does

**Comment by odwdinc** [comment]
Tagmo will not recognize it unless you go into the settings and turn off amiibo file browser, and even still, there's an error in loading the amiibo onto the nfc sticker. it should still work though.
